### ISSUE TITLE
Issues related to Spelling and Title of the forms .

### ISSUE THREAD

**Issue by SATYAJIT1910** [aghosh0605/XPerk-All_in_one_Microsoft_Activator#2]
1. Spelling mistake on Windows 10,8,7,8.1 Activation page heading i.e. Select Operating System Model. 'n' is missing.
2. Title of Windows 8,8.1,check_OS form needs to change from the default name. 
3. The size of the form1 is too big for small displays, it needs to be adjustable.
4. Icons need to be added to each form.
![image](https://user-images.githubusercontent.com/73009956/112726735-fe2f6880-8f44-11eb-9f32-3604832e4355.png)

![image](https://user-images.githubusercontent.com/73009956/112726757-1a330a00-8f45-11eb-8327-9fb779e6e912.png)

**Comment by aghosh0605** [comment]
will be fixed soon

**Comment by aghosh0605** [comment]
Done all tasks.
Check further...
